bogbon/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from . import views
from django.urls import path


app_name = 'mainapp'

urlpatterns = [
    # Ru
    path('', views.index, name='index'),
    path('news/', views.news_list, name='news_list'),
    path('articles/', views.article_list, name='article_list'),
    path('articles/<int:id>/', views.article_detail, name='article_detail'),
    path('shop/', views.product_list, name='product_list'),
    path('shop/<slug:category_slug>/', views.category_detail, name='category_detail'),
    path('about/', views.about, name='about'),
    path('seedlings/', views.seedling_list, name='seedling_list'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name="product_detail"),
    path('order/send/', views.OrderSend.as_view(), name="order_send"),
    # End Ru

    # En
    path('en/', views.index, name='index_en'),
    path('en/news/', views.news_list, name='news_list_en'),
    path('en/articles/', views.article_list, name='article_list_en'),
    path('en/articles/<int:id>/', views.article_detail, name='article_detail_en'),
    path('en/shop/', views.product_list, name='product_list_en'),
    path('en/shop/<slug:category_slug>/', views.category_detail, name='category_detail_en'),
    path('en/about/', views.about, name='about_en'),
    path('en/seedlings/', views.seedling_list, name='seedling_list_en'),
    path('en/product_detail/<int:pk>/', views.ProductDetailView.as_view(), name="product_detail_en"),
    path('en/order/send/', views.OrderSend.as_view(), name="order_send_en"),
    # End En

    # Uz
    path('uz/', views.index, name='index_uz'),
    path('uz/news/', views.news_list, name='news_list_uz'),
    path('uz/articles/', views.article_list, name='article_list_uz'),
    path('uz/articles/<int:id>/', views.article_detail, name='article_detail_uz'),
    path('uz/shop/', views.product_list, name='product_list_uz'),
    path('uz/shop/<slug:category_slug>/', views.category_detail, name='category_detail_uz'),
    path('uz/about/', views.about, name='about_uz'),
    path('uz/seedlings/', views.seedling_list, name='seedling_list_uz'),
    path('uz/product_detail/<int:pk>/', views.ProductDetailView.as_view(), name="product_detail_uz"),
    path('uz/order/send/', views.OrderSend.as_view(), name="order_send_uz"),
    # End Uz
]

mainapp/models.py
from django.db import models


class Article(models.Model):
    name = models.CharField(verbose_name='Название на русском', max_length=200)
    name_en = models.CharField(verbose_name='Название на английском', max_length=200)
    name_uz = models.CharField(verbose_name='Название на узбекском', max_length=200)
    pub_date = models.DateField(verbose_name='Дата публикации')
    author = models.CharField(verbose_name='Автор на русском', max_length=200)
    author_en = models.CharField(verbose_name='Автор на английском', max_length=200)
    author_uz = models.CharField(verbose_name='Автор на узбекском', max_length=200)
    short_description = models.TextField(verbose_name='Краткое описание на русском')
    short_description_en = models.TextField(verbose_name='Краткое описание на английском')
    short_description_uz = models.TextField(verbose_name='Краткое описание на узбекском')
    img_preview = models.ImageField(verbose_name='Миниатюра (334х234)', upload_to='article_img/')
    img_background = models.ImageField(verbose_name='Фоновое изображение (1920х1080)', upload_to='article_img/')
    img_post = models.ImageField(verbose_name='Изображение в статье (780х500)', upload_to='article_img/')
    text = models.TextField(verbose_name='Текст на русском')
    text_en = models.TextField(verbose_name='Текст на английском')
    text_uz = models.TextField(verbose_name='Текст на узбекском')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Category(models.Model):
    name_ru = models.CharField(verbose_name='Название категории на русском', max_length=200)
    name_uz = models.CharField(verbose_name='Название категории на узбекском', max_length=200)
    name_en = models.CharField(verbose_name='Название категории на английском', max_length=200)
    slug = models.SlugField(verbose_name='URL')

    def __str__(self):
        return self.name_ru

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('mainapp.Category', on_delete=models.PROTECT, verbose_name='Категория продукта',
                                blank=True, null=True, related_name='product')
    title_ru = models.CharField(verbose_name="Название продукта на русском", max_length=255)
    title_uz = models.CharField(verbose_name="Название продукта на узбекском", max_length=255)
    title_en = models.CharField(verbose_name="Название продукта на английском", max_length=255)
    subtitle_en = models.CharField(verbose_name="Подзаголовок на английском", max_length=500)
    subtitle_ru = models.CharField(verbose_name="Подзаголовок на русском", max_length=500)
    subtitle_uz = models.CharField(verbose_name="Подзаголовок на узбекском", max_length=500)
    price = models.FloatField(verbose_name='Цена продукта')
    show_price = models.FloatField(verbose_name='Показательная цена', blank=True, null=True)
    description_ru = models.TextField(verbose_name='Описание на русском')
    description_en = models.TextField(verbose_name='Описание на английском')
    description_uz = models.TextField(verbose_name='Описание на узбекском')
    img_hover = models.ImageField(verbose_name='Основное фото', upload_to='products/', blank=True, null=True)
    img_preview = models.ImageField(verbose_name='Фото при наведении', upload_to='products/', blank=True, null=True)

    def __str__(self):
        return self.title_ru

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductPhoto(models.Model):
    product = models.ForeignKey('mainapp.Product', on_delete=models.PROTECT, verbose_name='Товар')
    photo = models.ImageField(verbose_name='Фото продукта', upload_to='products/', blank=True, null=True)

    def __str__(self):
        return f"{self.product} | {self.photo}"

    class Meta:
        verbose_name = 'Фото продукта'
        verbose_name_plural = 'Фото продукта'

mainapp/views.py
from .models import Article, Category, Product, ProductPhoto
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from django.views.generic import TemplateView, View
from .bot import send_user_data_to_group
from django.db.models import Q


class ProductDetailView(TemplateView):
    def get_template_names(self):
        template = ''
        if '/uz/' in self.request.path:
            template = 'mainapp/product/product_detail_uz.html'
        elif '/en/' in self.request.path:
            template = 'mainapp/product/product_detail_en.html'
        else:
            template = 'mainapp/product/product_detail.html'
        return template

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        product = Product.objects.get(id=self.kwargs['pk'])
        product_photo = ProductPhoto.objects.filter(product_id=self.kwargs['pk'])
        similar_products = Product.objects.select_related('category') \
                               .filter(~Q(id=self.kwargs['pk']), category_id=product.category_id)[:4]
        context['product'] = product
        context['product_photo'] = product_photo
        context['similar_products'] = similar_products
        return context


class OrderSend(View):
    def post(self, request):
        product = Product.objects.get(id=request.POST.get('product_id'))
        send_user_data_to_group(request.POST, product.title_ru)
        if '/uz/' in request.path:
            return redirect('mainapp:product_detail_uz', pk=request.POST.get('product_id'))
        elif '/en/' in request.path:
            return redirect('mainapp:product_detail_en', pk=request.POST.get('product_id'))
        return redirect('mainapp:product_detail', pk=request.POST.get('product_id'))


def index(request):
    if '/uz/' in request.path:
        template = 'mainapp/index_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/index_en.html'
    else:
        template = 'mainapp/index.html'
    return render(request, template)


def news_list(request):
    if '/uz/' in request.path:
        template = 'mainapp/news_list_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/news_list_en.html'
    else:
        template = 'mainapp/news_list.html'
    return render(request, template)


def article_list(request):
    articles = Article.objects.all().order_by('-pub_date')
    context = {
        'articles': articles,
    }
    if '/uz/' in request.path:
        template = 'mainapp/article/article_list_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/article/article_list_en.html'
    else:
        template = 'mainapp/article/article_list.html'
    return render(request, template, context)


def article_detail(request, id):
    article = get_object_or_404(Article, id=id)
    context = {
        'article': article,
    }
    if '/uz/' in request.path:
        template = 'mainapp/article/article_detail_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/article/article_detail_en.html'
    else:
        template = 'mainapp/article/article_detail.html'
    return render(request, template, context)


def product_list(request):
    categories = Category.objects.prefetch_related('product').annotate(product_count=Count('product')).all()
    products = Product.objects.all()
    if request.GET.get('category_id'):
        products = products.filter(category_id=request.GET.get('category_id'))
    context = {
        'categories': categories,
        'products': products,
        'category_id': request.GET.get('category_id')
    }
    if '/uz/' in request.path:
        template = 'mainapp/product/product_list_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/product/product_list_en.html'
    else:
        template = 'mainapp/product/product_list.html'
    return render(request, template, context)


def category_detail(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    context = {
        'category': category,
    }
    if '/uz/' in request.path:
        template = 'mainapp/product/category_detail_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/product/category_detail_en.html'
    else:
        template = 'mainapp/product/category_detail.html'
    return render(request, template, context)


def about(request):
    if '/uz/' in request.path:
        template = 'mainapp/about_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/about_en.html'
    else:
        template = 'mainapp/about.html'
    return render(request, template)


def seedling_list(request):
    if '/uz/' in request.path:
        template = 'mainapp/seedling/seedling_list_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/seedling/seedling_list_en.html'
    else:
        template = 'mainapp/seedling/seedling_list.html'
    return render(request, template)

mainapp/templates/mainapp/product/product_detail.html
{% extends 'wrapper.html' %}
{% load static humanize %}
{% block title %}Статьи{% endblock %}
{% block content %}
    {% include 'blocks/header.html' %}
    <section class="p-0 mobile-height parallax mb-5" data-parallax-background-ratio="0.5"
             style="background-image: url('{% static 'img/home-corporate-parallex-bg.jpg' %}');">
        <div class="opacity-light bg-gradient-black-blue z-index-0"></div>
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-12 col-xl-6 col-lg-7 col-md-10 d-flex flex-column justify-content-center text-center full-screen position-relative z-index-1 md-landscape-h-600px">
                    <h2 class="text-white alt-font font-weight-600 letter-spacing-minus-1 text-shadow-large sm-no-text-shadow">
                        Товар {{ product.title_ru }} “IN VITRO”
                    </h2>
                </div>
            </div>
        </div>
    </section>

    <section class="big-section wow animate__fadeIn">
            <div class="container">
                <div class="row">
                    <div class="col-12 shopping-content d-flex flex-column flex-lg-row align-items-md-center">
                        <div class="w-60 md-w-100">
                            <div class="product-images-box lightbox-portfolio row">
                                <div class="col-12 col-lg-9 px-lg-0 order-lg-2 product-image md-margin-10px-bottom">
                                    <div class="swiper-container product-image-slider" data-slider-options='{ "spaceBetween": 10, "watchOverflow": true, "navigation": { "nextEl": ".slider-product-next", "prevEl": ".slider-product-prev" }, "thumbs": { "swiper": { "el": ".product-image-thumb", "slidesPerView": "auto", "spaceBetween": 15, "direction": "vertical", "navigation": { "nextEl": ".swiper-thumb-next", "prevEl": ".swiper-thumb-prev" } } } }' data-thumb-slider-md-direction="horizontal">
                                        <div class="swiper-wrapper">
                                            {% for photo in product_photo %}
                                                <div class="swiper-slide">
                                                    <a class="gallery-link" href="{{ photo.photo.url }}">
                                                        <img class="w-100" src="{{ photo.photo.url }}" alt="">
                                                    </a>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="slider-product-next swiper-button-next text-extra-dark-gray"><i class="fa fa-chevron-right"></i></div>
                                    <div class="slider-product-prev swiper-button-prev text-extra-dark-gray"><i class="fa fa-chevron-left"></i></div>
                                </div>
                                <div class="col-12 col-lg-3 order-lg-1 single-product-thumb md-margin-50px-bottom sm-margin-40px-bottom">
                                    <div class="swiper-container product-image-thumb slider-vertical padding-15px-lr padding-45px-bottom md-no-padding left-0px">
                                        <div class="swiper-wrapper">
                                            {% for photo in  product_photo %}
                                                <div class="swiper-slide">
                                                    <img class="w-100" src="{{ photo.photo.url }}" alt="">
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="swiper-thumb-next-prev text-center">
                                        <div class="swiper-button-prev swiper-thumb-prev"><i class="fa fa-chevron-up"></i></div>
                                        <div class="swiper-button-next swiper-thumb-next"><i class="fa fa-chevron-down"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="w-40 md-w-100 product-summary padding-7-rem-left lg-padding-5-rem-left md-no-padding-left">
                            <div class="breadcrumb text-small p-0">
                                <!-- start breadcrumb -->
                                <ul>
                                    <li><a href="{% url 'mainapp:product_list' %}">Магазин</a></li>
                                    <li>{{ product.title_ru }}</li>
                                </ul>
                                <!-- end breadcrumb -->
                            </div>
                            <div class="d-flex align-items-center margin-3-half-rem-tb md-margin-1-half-rem-tb">
                                <div class="flex-grow-1">
                                    <div class="text-extra-dark-gray font-weight-500 text-extra-large alt-font margin-5px-bottom">
                                        Название продукта: {{ product.title_ru }}
                                    </div>
                                    <span class="d-block">Краткое описание: {{ product.subtitle_ru }}</span>
                                    <span class="product-price text-extra-medium">Цена: <del>{{ product.show_price }} Сум</del>{{ product.price }} Сум</span>
                                </div>
                            </div>
                            <div class="last-paragraph-no-margin">
                                Описание: {{ product.description_ru | safe }}
                            </div>
                            <div class="mt-5">
                                <button type="button" data-toggle="modal"
                                    data-target="#exampleModal" class="btn btn-dark-gray btn-medium">
                                    Заказать
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </section>

        <section class="border-top border-width-1px border-color-medium-gray wow animate__fadeIn">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-lg-5 col-md-6 text-center margin-4-rem-bottom sm-margin-2-rem-bottom">
                        <span class="alt-font font-weight-500 text-uppercase d-inline-block margin-5px-bottom">
                            ВАМ ТАКЖЕ МОЖЕТ ПОНРАВИТЬСЯ
                        </span>
                        <h5 class="alt-font font-weight-500 text-extra-dark-gray letter-spacing-minus-1px">
                            Похожие продукты
                        </h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <ul class="product-listing shop-wrapper grid grid-loading grid-4col xl-grid-4col lg-grid-3col md-grid-2col sm-grid-2col xs-grid-1col gutter-extra-large text-center">
                            <li class="grid-sizer"></li>
                            {% for product in similar_products %}
                                <li class="grid-item">
                                    <div class="product-box">
                                        <div class="product-image border-radius-6px">
                                            <a href="{% url 'mainapp:product_detail' product.id %}">
                                                <img class="default-image"
                                                {% if product.img_preview %}
                                                    src="{{ product.img_preview.url }}"
                                                {% endif %}
                                                alt=""/>
                                                <img class="hover-image"
                                                {% if product.img_hover %}
                                                    src="{{ product.img_hover.url }}"
                                                {% endif %}
                                                alt=""/>
                                            </a>
                                            <div class="product-overlay bg-gradient-extra-midium-gray-transparent"></div>
                                            <div class="product-hover-bottom text-center padding-30px-tb">
                                                <a href="{% url 'mainapp:product_detail' product.id %}"
                                                    class="product-link-icon move-top-bottom"
                                                    data-toggle="tooltip" data-placement="top" title=""
                                                    data-original-title="Quick shop">
                                                    <i class="feather icon-feather-zoom-in"></i>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="product-footer text-center padding-25px-top xs-padding-10px-top">
                                            <a href="{% url 'mainapp:product_detail' product.id %}" class="text-extra-dark-gray font-weight-500 d-inline-block">{{ product.title_ru }}</a>
                                            <div class="product-price text-medium">{{ product.price }} Сум</div>
                                        </div>
                                    </div>
                                </li>
                                {% empty %}
                                <div>Товары не найдены</div>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <span class="modal-title" id="exampleModalLabel">
                    Ваш заказ будет отправлен к нам в офис, мы свяжемся с вами
                </span>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                    <form id="order_create_modal_form" action="{% url 'mainapp:order_send' %}" method="POST">
                        {% csrf_token %}
                        <input class="large-input margin-25px-bottom border-radius-0px required"
                        type="text" name="name" placeholder="Ваше имя" required />
                        <input class="large-input margin-25px-bottom border-radius-0px"
                        type="email" name="email" placeholder="Ваш адрес электронной почты" />
                        <input class="large-input margin-25px-bottom border-radius-0px"
                        type="tel" name="phone" placeholder="Номер мобильного телефона" required />
                        <input class="d-none" type="text" value="{{ product.id }}" name="product_id">
                    </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                <button type="submit" form="order_create_modal_form" class="btn btn-primary">Заказать</button>
              </div>
            </div>
          </div>
        </div>

    {% include 'blocks/footer.html' %}
    <a class="scroll-top-arrow" href="javascript:void(0);"><i class="feather icon-feather-arrow-up"></i></a>
{% endblock %}

{% block extra_js %}
<script>
</script>
{% endblock %}

mainapp/templates/mainapp/product/product_list.html
{% extends 'wrapper.html' %}
{% load static humanize %}
{% block title %}Статьи{% endblock %}
{% block content %}
    {% include 'blocks/header.html' %}
    <section class="p-0 mobile-height parallax mb-5" data-parallax-background-ratio="0.5"
                 style="background-image: url('{% static 'img/home-corporate-parallex-bg.jpg' %}');">
            <div class="opacity-light bg-gradient-black-blue z-index-0"></div>
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-12 col-xl-6 col-lg-7 col-md-10 d-flex flex-column justify-content-center text-center full-screen position-relative z-index-1 md-landscape-h-600px">
                        <h2 class="text-white alt-font font-weight-600 letter-spacing-minus-1 text-shadow-large sm-no-text-shadow">Товары “IN VITRO”</h2>
                    </div>
                </div>
            </div>
{#            <video class="d-xl-block d-none first-block__video" autoplay loop muted playsinline src="/static/img/bg.webm"></video>#}
        </section>

    <section class="shopping-left-side-bar pt-0">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-lg-9 col-md-8 shopping-content padding-55px-left md-padding-15px-left sm-margin-30px-bottom">
                        <ul class="product-listing shop-wrapper grid grid-loading grid-3col xl-grid-3col lg-grid-3col md-grid-2col sm-grid-2col xs-grid-1col gutter-large text-center">
                            <li class="grid-sizer"></li>
                            {% for product in products %}
                                <li class="grid-item wow animate__fadeIn">
                                    <div class="product-box margin-25px-bottom xs-margin-15px-bottom">
                                        <div class="product-image border-radius-6px">
                                            <a href="#">
                                                <img class="default-image" style="width: 100%; height: 40vh; object-fit: cover;"
                                                src="{% if product.img_preview %} {{ product.img_preview.url  }} {% endif %}"
                                                alt=""/>
                                                <img class="hover-image" style="width: 100%; height: 40vh; object-fit: cover;"
                                                src="{% if product.img_hover %} {{ product.img_hover.url  }} {% endif %}"
                                                alt=""/>
                                            </a>
                                            <div class="product-overlay bg-gradient-extra-midium-gray-transparent"></div>
                                            <div class="product-hover-bottom text-center padding-30px-tb">
                                                <a href="{% url 'mainapp:product_detail' product.id %}"
                                                class="product-link-icon move-top-bottom"
                                                data-toggle="tooltip"
                                                data-placement="top" title=""
                                                data-original-title="Посмотреть">
                                                    <i class="feather icon-feather-zoom-in"></i>
                                               </a>
                                            </div>
                                        </div>
                                        <div class="product-footer text-center padding-25px-top xs-padding-10px-top">
                                            <a href="#" class="text-extra-dark-gray font-weight-500 d-inline-block text-truncate">
                                                {{ product.title_ru }}
                                            </a>
                                            <div class="product-price text-medium">{{ product.price|intcomma }} Сум</div>
                                        </div>
                                    </div>
                                </li>
                                {% empty %}
                                <p>Товаров нет</p>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- start sidebar -->
                    <aside class="col-12 col-lg-3 col-md-4 shopping-sidebar">
                        <div class="border-bottom border-color-medium-gray padding-3-rem-bottom margin-3-rem-bottom wow animate__fadeIn">
                            <span class="shop-title alt-font font-weight-500 text-extra-dark-gray d-block margin-20px-bottom">Выберите категорию</span>
                            <form method="GET" action="{% url 'mainapp:product_list' %}" class="d-none category_filter_form">
                                <input name="category_id" type="text" value="" class="category_filter_form_input">
                                <input type="submit" class="category_filter_form_submit">
                            </form>
                            <ul class="list-style-07 filter-category">
                                {%  for category in categories %}
                                    <li class="category_filter_id" data-id="{{ category.id }}">
                                        <a href="#" {% if category.id|stringformat:"i" == category_id %} class="active" {% endif %}>
                                            <span class="product-cb product-category-cb"></span>
                                            {{ category.name_ru }}
                                        </a>
                                        <span class="item-qty">
                                            {{ category.product_count }}
                                        </span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </aside>
                    <!-- end sidebar -->
                </div>
            </div>
        </section>
    {# Footer #}
    {% include 'blocks/footer.html' %}
    {# End Footer #}
    {# ScrollTopButton #}
    <a class="scroll-top-arrow" href="javascript:void(0);"><i class="feather icon-feather-arrow-up"></i></a>
    {# End ScrollTopButton #}
{% endblock %}

{% block extra_js %}
<script>
    $(document).ready(function(){
        $('.category_filter_id').on('click', function() {
            $('.category_filter_form_input').val($(this).attr('data-id'))
            $('.category_filter_form_submit').click()
        })
    })
</script>
{% endblock %}