bogbon/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from . import views
from django.urls import path


app_name = 'mainapp'

urlpatterns = [
    # Ru
    path('', views.index, name='index'),
    path('news/', views.news_list, name='news_list'),
    path('articles/', views.article_list, name='article_list'),
    path('articles/<int:id>/', views.article_detail, name='article_detail'),
    path('shop/', views.product_list, name='product_list'),
    path('shop/<slug:category_slug>/', views.category_detail, name='category_detail'),
    path('about/', views.about, name='about'),
    path('seedlings/', views.seedling_list, name='seedling_list'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name="product_detail"),
    path('order/send/', views.OrderSend.as_view(), name="order_send"),
    # End Ru

    # En
    path('en/', views.index, name='index_en'),
    path('en/news/', views.news_list, name='news_list_en'),
    path('en/articles/', views.article_list, name='article_list_en'),
    path('en/articles/<int:id>/', views.article_detail, name='article_detail_en'),
    path('en/shop/', views.product_list, name='product_list_en'),
    path('en/shop/<slug:category_slug>/', views.category_detail, name='category_detail_en'),
    path('en/about/', views.about, name='about_en'),
    path('en/seedlings/', views.seedling_list, name='seedling_list_en'),
    path('en/product_detail/<int:pk>/', views.ProductDetailView.as_view(), name="product_detail_en"),
    path('en/order/send/', views.OrderSend.as_view(), name="order_send_en"),
    # End En

    # Uz
    path('uz/', views.index, name='index_uz'),
    path('uz/news/', views.news_list, name='news_list_uz'),
    path('uz/articles/', views.article_list, name='article_list_uz'),
    path('uz/articles/<int:id>/', views.article_detail, name='article_detail_uz'),
    path('uz/shop/', views.product_list, name='product_list_uz'),
    path('uz/shop/<slug:category_slug>/', views.category_detail, name='category_detail_uz'),
    path('uz/about/', views.about, name='about_uz'),
    path('uz/seedlings/', views.seedling_list, name='seedling_list_uz'),
    path('uz/product_detail/<int:pk>/', views.ProductDetailView.as_view(), name="product_detail_uz"),
    path('uz/order/send/', views.OrderSend.as_view(), name="order_send_uz"),
    # End Uz
]

mainapp/models.py
from django.db import models


class Article(models.Model):
    name = models.CharField(verbose_name='Название на русском', max_length=200)
    name_en = models.CharField(verbose_name='Название на английском', max_length=200)
    name_uz = models.CharField(verbose_name='Название на узбекском', max_length=200)
    pub_date = models.DateField(verbose_name='Дата публикации')
    author = models.CharField(verbose_name='Автор на русском', max_length=200)
    author_en = models.CharField(verbose_name='Автор на английском', max_length=200)
    author_uz = models.CharField(verbose_name='Автор на узбекском', max_length=200)
    short_description = models.TextField(verbose_name='Краткое описание на русском')
    short_description_en = models.TextField(verbose_name='Краткое описание на английском')
    short_description_uz = models.TextField(verbose_name='Краткое описание на узбекском')
    img_preview = models.ImageField(verbose_name='Миниатюра (334х234)', upload_to='article_img/')
    img_background = models.ImageField(verbose_name='Фоновое изображение (1920х1080)', upload_to='article_img/')
    img_post = models.ImageField(verbose_name='Изображение в статье (780х500)', upload_to='article_img/')
    text = models.TextField(verbose_name='Текст на русском')
    text_en = models.TextField(verbose_name='Текст на английском')
    text_uz = models.TextField(verbose_name='Текст на узбекском')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Category(models.Model):
    name_ru = models.CharField(verbose_name='Название категории на русском', max_length=200)
    name_uz = models.CharField(verbose_name='Название категории на узбекском', max_length=200)
    name_en = models.CharField(verbose_name='Название категории на английском', max_length=200)
    slug = models.SlugField(verbose_name='URL')

    def __str__(self):
        return self.name_ru

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('mainapp.Category', on_delete=models.PROTECT, verbose_name='Категория продукта',
                                blank=True, null=True, related_name='product')
    title_ru = models.CharField(verbose_name="Название продукта на русском", max_length=255)
    title_uz = models.CharField(verbose_name="Название продукта на узбекском", max_length=255)
    title_en = models.CharField(verbose_name="Название продукта на английском", max_length=255)
    subtitle_en = models.CharField(verbose_name="Подзаголовок на английском", max_length=500)
    subtitle_ru = models.CharField(verbose_name="Подзаголовок на русском", max_length=500)
    subtitle_uz = models.CharField(verbose_name="Подзаголовок на узбекском", max_length=500)
    price = models.FloatField(verbose_name='Цена продукта')
    show_price = models.FloatField(verbose_name='Показательная цена', blank=True, null=True)
    description_ru = models.TextField(verbose_name='Описание на русском')
    description_en = models.TextField(verbose_name='Описание на английском')
    description_uz = models.TextField(verbose_name='Описание на узбекском')
    img_hover = models.ImageField(verbose_name='Основное фото', upload_to='products/', blank=True, null=True)
    img_preview = models.ImageField(verbose_name='Фото при наведении', upload_to='products/', blank=True, null=True)

    def __str__(self):
        return self.title_ru

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductPhoto(models.Model):
    product = models.ForeignKey('mainapp.Product', on_delete=models.PROTECT, verbose_name='Товар')
    photo = models.ImageField(verbose_name='Фото продукта', upload_to='products/', blank=True, null=True)

    def __str__(self):
        return f"{self.product} | {self.photo}"

    class Meta:
        verbose_name = 'Фото продукта'
        verbose_name_plural = 'Фото продукта'

mainapp/views.py
from .models import Article, Category, Product, ProductPhoto
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from django.views.generic import TemplateView, View
from .bot import send_user_data_to_group
from django.db.models import Q


class ProductDetailView(TemplateView):
    def get_template_names(self):
        template = ''
        if '/uz/' in self.request.path:
            template = 'mainapp/product/product_detail_uz.html'
        elif '/en/' in self.request.path:
            template = 'mainapp/product/product_detail_en.html'
        else:
            template = 'mainapp/product/product_detail.html'
        return template

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        product = Product.objects.get(id=self.kwargs['pk'])
        product_photo = ProductPhoto.objects.filter(product_id=self.kwargs['pk'])
        similar_products = Product.objects.select_related('category') \
                               .filter(~Q(id=self.kwargs['pk']), category_id=product.category_id)[:4]
        context['product'] = product
        context['product_photo'] = product_photo
        context['similar_products'] = similar_products
        return context


class OrderSend(View):
    def post(self, request):
        product = Product.objects.get(id=request.POST.get('product_id'))
        send_user_data_to_group(request.POST, product.title_ru)
        if '/uz/' in request.path:
            return redirect('mainapp:product_detail_uz', pk=request.POST.get('product_id'))
        elif '/en/' in request.path:
            return redirect('mainapp:product_detail_en', pk=request.POST.get('product_id'))
        return redirect('mainapp:product_detail', pk=request.POST.get('product_id'))


def index(request):
    if '/uz/' in request.path:
        template = 'mainapp/index_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/index_en.html'
    else:
        template = 'mainapp/index.html'
    return render(request, template)


def news_list(request):
    if '/uz/' in request.path:
        template = 'mainapp/news_list_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/news_list_en.html'
    else:
        template = 'mainapp/news_list.html'
    return render(request, template)


def article_list(request):
    articles = Article.objects.all().order_by('-pub_date')
    context = {
        'articles': articles,
    }
    if '/uz/' in request.path:
        template = 'mainapp/article/article_list_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/article/article_list_en.html'
    else:
        template = 'mainapp/article/article_list.html'
    return render(request, template, context)


def article_detail(request, id):
    article = get_object_or_404(Article, id=id)
    context = {
        'article': article,
    }
    if '/uz/' in request.path:
        template = 'mainapp/article/article_detail_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/article/article_detail_en.html'
    else:
        template = 'mainapp/article/article_detail.html'
    return render(request, template, context)


def product_list(request):
    categories = Category.objects.prefetch_related('product').annotate(product_count=Count('product')).all()
    products = Product.objects.all()
    if request.GET.get('category_id'):
        products = products.filter(category_id=request.GET.get('category_id'))
    context = {
        'categories': categories,
        'products': products,
        'category_id': request.GET.get('category_id')
    }
    if '/uz/' in request.path:
        template = 'mainapp/product/product_list_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/product/product_list_en.html'
    else:
        template = 'mainapp/product/product_list.html'
    return render(request, template, context)


def category_detail(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    context = {
        'category': category,
    }
    if '/uz/' in request.path:
        template = 'mainapp/product/category_detail_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/product/category_detail_en.html'
    else:
        template = 'mainapp/product/category_detail.html'
    return render(request, template, context)


def about(request):
    if '/uz/' in request.path:
        template = 'mainapp/about_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/about_en.html'
    else:
        template = 'mainapp/about.html'
    return render(request, template)


def seedling_list(request):
    if '/uz/' in request.path:
        template = 'mainapp/seedling/seedling_list_uz.html'
    elif '/en/' in request.path:
        template = 'mainapp/seedling/seedling_list_en.html'
    else:
        template = 'mainapp/seedling/seedling_list.html'
    return render(request, template)

mainapp/templates/blocks/footer.html
{% load static %}
<footer class="footer-dark bg-slate-blue">
    <div class="footer-top padding-five-tb lg-padding-eight-tb md-padding-50px-tb">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-3 col-md-5 col-sm-6 order-sm-1 order-lg-0 md-margin-50px-bottom xs-margin-25px-bottom">
                    {% if '/en/' in request.path %}
                        <a href="{% url 'mainapp:index_en' %}" class="footer-logo margin-20px-bottom d-block"><img
                                src="{% static 'img/logo-white.png' %}" data-at2x="images/logo-white@2x.png" alt=""></a>
                        <p class="w-80 sm-w-100 margin-20px-bottom">A modern in vitro laboratory was built and launched
                            in 2020 as part of the Bogbon agricultural complex.</p>
                    {% elif '/uz/' in request.path %}
                        <a href="{% url 'mainapp:index_uz' %}" class="footer-logo margin-20px-bottom d-block"><img
                                src="{% static 'img/logo-white.png' %}" data-at2x="images/logo-white@2x.png" alt=""></a>
                        <p class="w-80 sm-w-100 margin-20px-bottom">“Боғбон” агрокомплекси таркибида 2020 йилда
                            замонавий “In vitro” лабораторияси барпо этилди ва ишга туширилди.</p>
                    {% else %}
                        <a href="{% url 'mainapp:index' %}" class="footer-logo margin-20px-bottom d-block"><img
                                src="{% static 'img/logo-white.png' %}" data-at2x="images/logo-white@2x.png" alt=""></a>
                        <p class="w-80 sm-w-100 margin-20px-bottom">Современная лаборатория In vitro построена и
                            запущена в 2020 году в составе агрокомплекса Bogbon.</p>
                    {% endif %}
                    <div class="social-icon-style-12">
                        <ul class="extra-small-icon light">
                            <li><a class="facebook" href="https://www.facebook.com/" target="_blank"><i
                                    class="fab fa-facebook-f"></i></a></li>
                            <li><a class="dribbble" href="http://www.dribbble.com" target="_blank"><i
                                    class="fab fa-dribbble"></i></a></li>
                            <li><a class="twitter" href="http://www.twitter.com" target="_blank"><i
                                    class="fab fa-twitter"></i></a></li>
                            <li><a class="instagram" href="http://www.instagram.com" target="_blank"><i
                                    class="fab fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-12 col-lg-2 col-sm-4 order-sm-3 order-lg-0 xs-margin-25px-bottom">
                    {% if '/en/' in request.path %}
                        <span class="alt-font font-weight-500 d-block text-white margin-20px-bottom xs-margin-10px-bottom">Company</span>
                        <ul>
                            <li><a href="{% url 'mainapp:article_list_en' %}">Articles</a></li>
                        </ul>
                    {% elif '/uz/' in request.path %}
                        <span class="alt-font font-weight-500 d-block text-white margin-20px-bottom xs-margin-10px-bottom">Kompaniya</span>
                        <ul>
                            <li><a href="{% url 'mainapp:article_list_uz' %}">Maqolalar</a></li>
                        </ul>
                    {% else %}
                        <span class="alt-font font-weight-500 d-block text-white margin-20px-bottom xs-margin-10px-bottom">Компания</span>
                        <ul>
                            <li><a href="{% url 'mainapp:article_list' %}">Статьи</a></li>
                        </ul>
                    {% endif %}
                </div>
                <div class="col-12 col-lg-2 col-sm-4 order-sm-4 order-lg-0 xs-margin-25px-bottom">
                    {% if '/en/' in request.path %}
                        <span class="alt-font font-weight-500 d-block text-white margin-20px-bottom xs-margin-10px-bottom">Customer</span>
                        <ul>
                            <li><a href="{% url 'mainapp:product_list_en' %}">Shop</a></li>
                            <li><a href="{% url 'mainapp:index_en' %}">Client support</a></li>
                        </ul>
                    {% elif '/uz/' in request.path %}
                        <span class="alt-font font-weight-500 d-block text-white margin-20px-bottom xs-margin-10px-bottom">Mijoz</span>
                        <ul>
                            <li><a href="{% url 'mainapp:product_list_uz' %}">Do'kon</a></li>
                            <li><a href="{% url 'mainapp:index_uz' %}">Mijozlarni qo'llab-quvvatlash</a></li>
                        </ul>
                    {% else %}
                        <span class="alt-font font-weight-500 d-block text-white margin-20px-bottom xs-margin-10px-bottom">Клиентам</span>
                        <ul>
                            <li><a href="{% url 'mainapp:product_list' %}">Магазин</a></li>
                            <li><a href="{% url 'mainapp:index' %}">Клиентская поддержка</a></li>
                        </ul>
                    {% endif %}
                </div>
                <div class="col-12 col-lg-2 col-sm-4 order-sm-5 order-lg-0 xs-margin-25px-bottom">
                    {% if '/en/' in request.path %}
                        <span class="alt-font font-weight-500 d-block text-white margin-20px-bottom xs-margin-10px-bottom">Additional</span>
                        <ul>
                            <li><a href="{% url 'mainapp:index_en' %}">Our story</a></li>
                        </ul>
                    {% elif '/uz/' in request.path %}
                        <span class="alt-font font-weight-500 d-block text-white margin-20px-bottom xs-margin-10px-bottom">Qo'shimcha</span>
                        <ul>
                            <li><a href="{% url 'mainapp:index_uz' %}">Bizning hikoyamiz</a></li>
                        </ul>
                    {% else %}
                        <span class="alt-font font-weight-500 d-block text-white margin-20px-bottom xs-margin-10px-bottom">Дополнительно</span>
                        <ul>
                            <li><a href="{% url 'mainapp:index' %}">Наша история</a></li>
                        </ul>
                    {% endif %}
                </div>
                <div class="col-12 col-lg-3 col-md-5 col-sm-6 order-sm-2 order-lg-0 md-margin-50px-bottom xs-no-margin-bottom">
                    {% if '/en/' in request.path %}
                        <span class="alt-font font-weight-500 d-block text-white margin-30px-bottom xs-margin-25px-bottom">Latest news</span>
                    {% elif '/uz/' in request.path %}
                        <span class="alt-font font-weight-500 d-block text-white margin-30px-bottom xs-margin-25px-bottom">So'ngi yangiliklar</span>
                    {% else %}
                        <span class="alt-font font-weight-500 d-block text-white margin-30px-bottom xs-margin-25px-bottom">Последние новости</span>
                    {% endif %}
                    <ul>
                        <li class="media">
                            <a href="blog-post-layout-01.html"
                               class="w-75px margin-30px-right sm-margin-15px-right xs-margin-30px-right">
                                <img src="{% static 'img/blog-img80.jpg' %}" alt="">
                            </a>
                            <div class="media-body">
                                {% if '/en/' in request.path %}
                                    <a href="{% url 'mainapp:index_en' %}">Text of the first post...</a>
                                {% elif '/uz/' in request.path %}
                                    <a href="{% url 'mainapp:index_uz' %}">Birinchi xabar matni...</a>
                                {% else %}
                                    <a href="{% url 'mainapp:index' %}">Текст первого поста...</a>
                                {% endif %}
                            </div>
                        </li>
                        <li class="media">
                            <a href="blog-post-layout-02.html"
                               class="w-75px margin-30px-right sm-margin-15px-right xs-margin-30px-right">
                                <img src="{% static 'img/blog-img79.jpg' %}" alt="">
                            </a>
                            <div class="media-body">
                                {% if '/en/' in request.path %}
                                    <a href="{% url 'mainapp:index_en' %}">Text of the second post...</a>
                                {% elif '/uz/' in request.path %}
                                    <a href="{% url 'mainapp:index_uz' %}">Ikkinchi xabar matni...</a>
                                {% else %}
                                    <a href="{% url 'mainapp:index' %}">Текст второго поста...</a>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom padding-35px-tb border-top border-color-white-transparent">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 sm-margin-10px-bottom xs-margin-15px-bottom">
                    <ul class="footer-horizontal-link d-flex flex-column flex-sm-row justify-content-sm-center justify-content-md-start">
                        {% if '/en/' in request.path %}
                            <li><a href="{% url 'mainapp:index_en' %}">Privacy policy</a></li>
                        {% elif '/uz/' in request.path %}
                            <li><a href="{% url 'mainapp:index_uz' %}">Maxfiylik siyosati</a></li>
                        {% else %}
                            <li><a href="{% url 'mainapp:index' %}">Политика конфиденциальности</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-12 col-md-6 text-left text-sm-center text-md-right last-paragraph-no-margin">
                    {% if '/en/' in request.path %}
                        <p>&copy; 2021 Bog'bon. All rights reserved</p>
                    {% elif '/uz/' in request.path %}
                        <p>&copy; 2021 Bog'bon. Barcha huquqlar himoyalangan</p>
                    {% else %}
                        <p>&copy; 2021 Bog'bon. Все права защищены</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</footer>

mainapp/templates/blocks/header.html
{% load static %}
<header>
    {# Navigation #}
    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent header-light fixed-top navbar-boxed header-reverse-scroll">
        <div class="container-fluid nav-header-container">
            <div class="col-auto col-sm-6 col-lg-2 mr-auto pl-lg-0">
                {% if '/en/' in request.path %}
                    <a class="navbar-brand" href="{% url 'mainapp:index_en' %}">
                {% elif '/uz/' in request.path %}
                    <a class="navbar-brand" href="{% url 'mainapp:index_uz' %}">
                {% else %}
                    <a class="navbar-brand" href="{% url 'mainapp:index' %}">
                {% endif %}
                <img src="{% static 'img/logo-white.png' %}" class="default-logo" alt="">
                <img src="{% static 'img/logo-green-dark.png' %}" class="alt-logo" alt="">
                <img src="{% static 'img/logo-black.png' %}" class="mobile-logo" alt="">
                </a>
            </div>
            <div class="col-auto col-lg-8 menu-order px-lg-0">
                <button class="navbar-toggler float-right" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-label="Toggle navigation">
                    <span class="navbar-toggler-line"></span>
                    <span class="navbar-toggler-line"></span>
                    <span class="navbar-toggler-line"></span>
                    <span class="navbar-toggler-line"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                    <ul class="navbar-nav alt-font">
                        {% if '/en/' in request.path %}
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:index_en' %}" class="nav-link">Home</a>
                            </li>
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:article_list_en' %}" class="nav-link">Articles</a>
                            </li>
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:product_list_en' %}" class="nav-link">Shop</a>
                            </li>
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:about_en' %}" class="nav-link">About</a>
                            </li>
                        {% elif '/uz/' in request.path %}
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:index_uz' %}" class="nav-link">Bosh sahifa</a>
                            </li>
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:article_list_uz' %}" class="nav-link">Maqolalar</a>
                            </li>
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:product_list_uz' %}" class="nav-link">Do'kon</a>
                            </li>
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:about_uz' %}" class="nav-link">Kompaniya haqida</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:index' %}" class="nav-link">Главная</a>
                            </li>
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:article_list' %}" class="nav-link">Статьи</a>
                            </li>
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:product_list' %}" class="nav-link">Магазин</a>
                            </li>
                            <li class="nav-item dropdown megamenu">
                                <a href="{% url 'mainapp:about' %}" class="nav-link">О компании</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="col-auto col-lg-2 text-right pr-0 font-size-0">
                <div class="header-social-icon d-inline-block">
                    {# Path will get from JS #}
                    <a href="#" id="header_language_ru"><i>Ru</i></a>
                    <a href="#" id="header_language_uz"><i>Uz</i></a>
                    <a href="#" id="header_language_en"><i>En</i></a>
                </div>
            </div>
        </div>
    </nav>
    {# End Navigation #}
</header>